name: aani_generator
description: Generate json with us.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animations: ^2.0.2
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.0
  provider: ^6.0.3
  file_picker: ^5.2.0+1
  shared_preferences: ^2.0.9
  bitsdojo_window: ^0.1.2
  flutter_highlight: ^0.7.0
  http: ^0.13.5
  mime: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Sans
      fonts:
        - asset: fonts/bold.ttf
          weight: 700
          style: normal
        - asset: fonts/bold_italic.ttf
          weight: 700
          style: italic
        - asset: fonts/medium.ttf
          weight: 500
          style: normal
        - asset: fonts/medium_italic.ttf
          weight: 500
          style: italic
        - asset: fonts/regular.ttf
          weight: 300
          style: normal
        - asset: fonts/italic.ttf
          weight: 300
          style: italic
